// Generates the sample dataset used by the dashboard.
// Deterministic (seeded LCG) so regenerating never churns the diff.
import { writeFileSync, mkdirSync } from 'node:fs';

let seed = 20260823;
const rand = () => (seed = (seed * 1664525 + 1013904223) % 4294967296) / 4294967296;
const jitter = (amp) => 1 + (rand() - 0.5) * amp;

const MONTHS = [
  '2025-09', '2025-10', '2025-11', '2025-12', '2026-01', '2026-02',
  '2026-03', '2026-04', '2026-05', '2026-06', '2026-07', '2026-08',
];

// Per-channel shape: base monthly spend, growth per month, cost per MQL,
// MQL->SQL rate, SQL->win rate, average contract value. Cost per MQL is derived
// from a target CAC (cpm = CAC x sqlRate x winRate) so the unit economics agree.
const CHANNELS = [
  { id: 'paid-search', name: 'Paid search',    slot: 1, spend: 92000, growth: 0.012, cpm: 823, sqlRate: 0.34, winRate: 0.22, acv: 34000 },
  { id: 'paid-social', name: 'Paid social',    slot: 2, spend: 61000, growth: 0.021, cpm: 497, sqlRate: 0.23, winRate: 0.16, acv: 33000 },
  { id: 'organic',     name: 'Organic / SEO',  slot: 3, spend: 38000, growth: 0.028, cpm: 576, sqlRate: 0.41, winRate: 0.27, acv: 21000 },
  { id: 'email',       name: 'Lifecycle email',slot: 4, spend: 17000, growth: 0.009, cpm: 620, sqlRate: 0.38, winRate: 0.24, acv: 19000 },
];

// Q4 push, January reset, spring ramp.
const SEASON = [1.0, 1.06, 1.14, 0.88, 0.92, 1.02, 1.09, 1.07, 1.04, 1.11, 1.05, 1.12];

const series = [];
CHANNELS.forEach((c) => {
  MONTHS.forEach((month, i) => {
    const spend = Math.round(c.spend * Math.pow(1 + c.growth, i) * SEASON[i] * jitter(0.10));
    const cpm = c.cpm * jitter(0.12) * (1 + i * 0.004); // costs creep up over the year
    const mqls = Math.round(spend / cpm);
    const sqls = Math.round(mqls * c.sqlRate * jitter(0.10));
    const customers = Math.round(sqls * c.winRate * jitter(0.14));
    const pipeline = Math.round(sqls * c.acv * jitter(0.08));
    const revenue = Math.round(customers * c.acv * jitter(0.06));
    series.push({ month, channel: c.id, spend, mqls, sqls, customers, pipeline, revenue });
  });
});

// Funnel counts are anchored to the MQL total so the two views agree.
const totalMqls = series.reduce((s, r) => s + r.mqls, 0);
const funnel = {
  ratios: [
    { id: 'sessions', name: 'Sessions', perMql: 41.0 },
    { id: 'leads', name: 'Leads', perMql: 3.4 },
    { id: 'mqls', name: 'MQLs', perMql: 1 },
    { id: 'sqls', name: 'SQLs', perMql: 0.32 },
    { id: 'customers', name: 'Customers', perMql: 0.071 },
  ],
};

const data = {
  meta: {
    title: 'Marketing performance',
    generated: '2026-08-23',
    note: 'Sample data. Replace assets/data.js with a feed from your own warehouse or analytics stack.',
    currency: 'USD',
  },
  targets: { cac: 9500, roas: 3.2, mqlToSql: 0.33, pipelinePerMonth: 3100000 },
  months: MONTHS,
  channels: CHANNELS.map(({ id, name, slot }) => ({ id, name, slot })),
  funnel,
  series,
  totals: { mqls: totalMqls },
};

mkdirSync('data', { recursive: true });
mkdirSync('assets', { recursive: true });
writeFileSync('data/metrics.json', JSON.stringify(data, null, 2) + '\n');
writeFileSync(
  'assets/data.js',
  '// Generated by scripts/generate-data.mjs — do not edit by hand.\n' +
  'window.DASHBOARD_DATA = ' + JSON.stringify(data) + ';\n'
);
console.log(`wrote ${series.length} rows across ${CHANNELS.length} channels x ${MONTHS.length} months`);
